rename redhat-cop to konveyor where appropriate
konveyor/pelorus pull request #377
Opened 2022-02-25 21:35 UTC by weshayutin

* Rename redhat-cop to konveyor where appropriate

## Describe the behavior changes introduced in this PR
none, just renaming the git url

## Linked Issues?
** https://github.com/konveyor/pelorus/issues/351 **

resolves #351 <-- Use this if merging should auto-close an issue

related to #<issue number> <-- Use this if it shouldn't

## Testing Instructions

Please include any additional commands or pointers in addition to our [standard PR testing process](/docs/Development.md#testing-pull-requests).

@redhat-cop/mdt

2022-02-25 22:00 UTC, mpryc approved these changes

2022-02-25 22:03 UTC, mpryc commented
@weshayutin if you are doing any change to the Charts they require version bump. There is script for that.

2022-02-25 22:06 UTC, mpryc requested changes
As in my comment, required chart version bump.

2022-02-28 14:22 UTC, weshayutin commented
@mpryc ok.. thanks for the review!  I'll review the developer guide and scripts :)
Thank you

2022-02-28 20:21 UTC, KevinMGranger requested changes
Aside from the one newline thing, this looks good to me!

2022-02-28 20:21 UTC, KevinMGranger commented on docs/Development.md
> -1. Update the default exporter tag version to the new tag you're about to make.
Two trailing spaces in markdown is significant. It puts a `<br>` instead of starting a new `<p>`. Can you put these back?

2022-03-04 20:16 UTC, weshayutin commented
OK.. thanks for the review Kevin, Michal.
I scanned the markdown files for other places where two spaces impacted the indentation as well and I think I found them all.
bumped the chart to $next 1.4.8

thanks again!

2022-03-05 23:31 UTC, mpryc approved these changes

2022-03-14 17:49 UTC, KevinMGranger requested changes
Once the Chart.yaml conflicts are fixed, this is good to go!

2022-03-14 19:45 UTC, mpryc approved these changes

2022-03-14 20:57 UTC, KevinMGranger approved these changes

2022-03-14 20:57 UTC, merged