Troubleshooting docs and tool(s)
konveyor/pelorus pull request #615
Opened 2022-08-29 15:54 UTC by KevinMGranger

## Describe the behavior changes introduced in this PR
Add docs for troubleshooting and a script to check for mislabeled resources.

## Linked Issues?

resolves #549

## Testing Instructions

- [ ] todo

2022-09-09 12:58 UTC, weshayutin commented
/check all

2022-09-13 22:07 UTC, KevinMGranger commented
@weshayutin @mpryc the script is ready for testing. Will add docs tomorrow.

2022-09-14 09:38 UTC, mpryc requested changes
To be fixed:
  1. when using json different stream or option to disable log should be implemented, otherwise it's hard for the jq or others to parse output.
  2. running script without any flags or with help connects to the cluster first and then parses arguments, should be other way around (why to do any processing if input parameters are wrong?)
  3. running without exporter specified gives some wired output:
   ```$ ./scripts/troubleshooting/missing_labels --namespace basic-python-tekton
    Running troubleshooting exporter. No version information found.
    Initializing Logger with LogLevel: INFO
    09-14-2022 11:27:04 ERROR    load cache error: ResourceList.__init__() got an unexpected keyword argument 'base_resource_lookup'
    Unknown exporter for troubleshooting: i

   $ $ ./scripts/troubleshooting/missing_labels --namespace default
    Running troubleshooting exporter. No version information found.
    Initializing Logger with LogLevel: INFO
    09-14-2022 11:27:59 ERROR    load cache error: ResourceList.__init__() got an unexpected keyword argument 'base_resource_lookup'
    Unknown exporter for troubleshooting: l
```

Quersions rather then request to change:

4. what if the exporter was deployed with different APP_LABEL, I see it's working but to run this script I had to, will this be documented somewhere?
   export APP_LABEL=app.kubernetes.io/my_label

5. for the build it's checking only if it's missing label, which is OK. Later it could be extended to check for specific metadata such as git url or annotation ?

2022-09-14 14:13 UTC, KevinMGranger commented
> when using json different stream or option to disable log should be implemented, otherwise it's hard for the jq or others to parse output.

Agreed. I have another branch full of misc. fixes that includes this, I think.

> running script without any flags or with help connects to the cluster first and then parses arguments, should be other way around (why to do any processing if input parameters are wrong?)

Agreed

> (weird flag error)

Looking into it.

> what if the exporter was deployed with different APP_LABEL, I see it's working but to run this script I had to, will this be documented somewhere?

Yes, I should and will document it.

> for the build it's checking only if it's missing label, which is OK. Later it could be extended to check for specific metadata such as git url or annotation ?

Also agreed! Will file an issue for it after this is done.

2022-09-14 19:04 UTC, mpryc approved these changes
/lgtm

2022-09-14 20:01 UTC, mpryc commented
/test 4.9-e2e-openshift

2022-09-14 21:20 UTC, merged